# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# vmImage: 'vs2017-win2016'

trigger:
- master
- galleon/azure-pipelines

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    continueOnError: false
    pool:
      vmImage: 'windows-2019'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 2
    variables:
      BOOST_ROOT: 'C:\hostedtoolcache\windows\Boost\1.72.0\x86_64'
    steps:
    - checkout: self
      submodules: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install torch>=1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
      displayName: 'Install requirements'
    - script: |
        echo $(BOOST_ROOT)
        echo $(BOOST_ROOT_1_72_0)
      displayName: 'Set BOOST_ROOT variable'
    - script: |
        python setup.py sdist bdist_wheel --cpp-extension
      displayName: 'Build using setup.py'
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows
- stage: Deploy
  jobs:
  - job: Deplo
    steps:
    - script: echo Deploying the wheel
